
import java.awt.Color;
import java.awt.Dialog;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rylle
 */
public class Dashboard extends javax.swing.JFrame {
private static boolean userClick = false;
private static boolean packageClick = false;
private static ImageIcon rightIcon;
private static Image rightImage;
private static ImageIcon rightIconResize;
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        /* Hide Jpanel4 */
        jPanel4.hide();
        
        /* Hide Jpanel5 */
        jPanel5.hide();
        
        /* Home Icon */
        ImageIcon homeIcon = new ImageIcon(getClass().getResource("/home.png"));
        Image homeImage = homeIcon.getImage();
        ImageIcon homeIconResize = new ImageIcon(homeImage.getScaledInstance(30, 30, 0));
        jLabel1.setIcon(homeIconResize);
        
        /* User Icon */
        ImageIcon userIcon = new ImageIcon(getClass().getResource("/user.png"));
        Image userImage = userIcon.getImage();
        ImageIcon userIconResize = new ImageIcon(userImage.getScaledInstance(35, 30, 0));
        jLabel2.setIcon(userIconResize);
        
        /* Add User Icon */
        ImageIcon AdduserIcon = new ImageIcon(getClass().getResource("/user-add.png"));
        Image AdduserImage = AdduserIcon.getImage();
        ImageIcon AdduserIconResize = new ImageIcon(AdduserImage.getScaledInstance(35, 30, 0));
        jLabel3.setIcon(AdduserIconResize);
        
        /* Users Icon */
        ImageIcon usersIcon = new ImageIcon(getClass().getResource("/users.png"));
        Image usersImage = usersIcon.getImage();
        ImageIcon usersIconResize = new ImageIcon(usersImage.getScaledInstance(35, 30, 0));
        jLabel4.setIcon(usersIconResize);
        
        /* Add Angle Rigth Icon */
        rightIcon = new ImageIcon(getClass().getResource("/angle-right.png"));
        rightImage = rightIcon.getImage();
        rightIconResize = new ImageIcon(rightImage.getScaledInstance(20, 20, 0));
        
        /* Box Icon */
        ImageIcon boxIcon = new ImageIcon(getClass().getResource("/box-alt.png"));
        Image boxImage = boxIcon.getImage();
        ImageIcon boxIconResize = new ImageIcon(boxImage.getScaledInstance(30, 30, 0));
        jLabel6.setIcon(boxIconResize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new JPanel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jPanel5 = new JPanel();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        jDialog1 = new JDialog();
        jPanel6 = new JPanel();
        jPanel1 = new JPanel();
        jPanel2 = new JPanel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel6 = new JLabel();
        jLabel10 = new JLabel();
        jLabel11 = new JLabel();
        jPanel3 = new JPanel();
        jInternalFrame1 = new JInternalFrame();

        jPanel4.setBackground(new Color(153, 153, 153));
        jPanel4.setBorder(BorderFactory.createLineBorder(new Color(255, 255, 255)));
        jPanel4.setName("jPanel4"); // NOI18N

        jLabel3.setFont(new Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel3.setForeground(new Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel3.setText("  ADD USER");
        jLabel3.setBorder(BorderFactory.createLineBorder(new Color(255, 255, 255)));
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setFont(new Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel4.setForeground(new Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel4.setText("  ALL USER");
        jLabel4.setBorder(BorderFactory.createLineBorder(new Color(255, 255, 255)));
        jLabel4.setName("jLabel4"); // NOI18N

        GroupLayout jPanel4Layout = new GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 230, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 230, GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new Color(153, 153, 153));
        jPanel5.setBorder(BorderFactory.createLineBorder(new Color(255, 255, 255)));
        jPanel5.setName("jPanel5"); // NOI18N

        jLabel7.setFont(new Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel7.setForeground(new Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel7.setText(" ADD PACAKGES");
        jLabel7.setBorder(BorderFactory.createLineBorder(new Color(255, 255, 255)));
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setFont(new Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel8.setForeground(new Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel8.setText(" ALL PACAKGES");
        jLabel8.setBorder(BorderFactory.createLineBorder(new Color(255, 255, 255)));
        jLabel8.setName("jLabel8"); // NOI18N

        GroupLayout jPanel5Layout = new GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 230, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 230, GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jDialog1.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        jDialog1.setName("jDialog1"); // NOI18N

        jPanel6.setName("jPanel6"); // NOI18N

        GroupLayout jPanel6Layout = new GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 848, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        GroupLayout jDialog1Layout = new GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(jDialog1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(jDialog1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("ISP MANAGEMENT SYSTEM");
        setName("Form"); // NOI18N

        jPanel1.setBackground(new Color(204, 204, 204));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new AbsoluteLayout());

        jPanel2.setBackground(new Color(153, 153, 153));
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new AbsoluteLayout());

        jLabel1.setBackground(new Color(153, 153, 153));
        jLabel1.setFont(new Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setForeground(new Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setText(" HOME");
        jLabel1.setBorder(BorderFactory.createLineBorder(new Color(255, 255, 255)));
        jLabel1.setName("jLabel1"); // NOI18N
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new AbsoluteConstraints(0, 200, 230, 60));

        jLabel2.setBackground(new Color(153, 153, 153));
        jLabel2.setFont(new Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel2.setForeground(new Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel2.setText(" USER");
        jLabel2.setBorder(BorderFactory.createLineBorder(new Color(255, 255, 255)));
        jLabel2.setName("jLabel2"); // NOI18N
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new AbsoluteConstraints(0, 280, 230, 60));

        jLabel6.setBackground(new Color(153, 153, 153));
        jLabel6.setFont(new Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel6.setForeground(new Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel6.setText(" PACKAGES");
        jLabel6.setBorder(BorderFactory.createLineBorder(new Color(255, 255, 255)));
        jLabel6.setName("jLabel6"); // NOI18N
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new AbsoluteConstraints(0, 360, 230, 60));

        jLabel10.setBackground(new Color(153, 153, 153));
        jLabel10.setFont(new Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel10.setForeground(new Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel10.setText("BILLS");
        jLabel10.setBorder(BorderFactory.createLineBorder(new Color(255, 255, 255)));
        jLabel10.setName("jLabel10"); // NOI18N
        jLabel10.setOpaque(true);
        jLabel10.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel10, new AbsoluteConstraints(0, 520, 230, 60));

        jLabel11.setBackground(new Color(153, 153, 153));
        jLabel11.setFont(new Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel11.setForeground(new Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel11.setText("PAYMENT");
        jLabel11.setBorder(BorderFactory.createLineBorder(new Color(255, 255, 255)));
        jLabel11.setName("jLabel11"); // NOI18N
        jLabel11.setOpaque(true);
        jLabel11.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel11, new AbsoluteConstraints(0, 440, 230, 60));

        jPanel1.add(jPanel2, new AbsoluteConstraints(0, 0, 230, 780));

        jPanel3.setBackground(new Color(204, 204, 204));
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new AbsoluteLayout());

        jInternalFrame1.setName("jInternalFrame1"); // NOI18N
        jInternalFrame1.setVisible(true);

        GroupLayout jInternalFrame1Layout = new GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(jInternalFrame1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(jInternalFrame1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.add(jInternalFrame1, new AbsoluteConstraints(70, 30, 830, 520));

        jPanel1.add(jPanel3, new AbsoluteConstraints(230, 0, 1070, 780));

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
    // TODO add your handling code here:
        if (userClick) {
            
            /* Hide Jpanel4 */
            jPanel4.hide();
            userClick = false;
            jLabel2.setBackground(new Color(153,153,153));
        }else{
            int position = 1;
            selector(position);
        
            /* Show Jpanel4 */
            jPanel4.show();
            userClick = true;
            
           /* Hide Jpanel5 */
           jPanel5.hide();
           packageClick = false;
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel6MouseClicked(MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        
        if (packageClick) {
            
            /* Hide Jpanel5 */
            jPanel5.hide();
            packageClick = false;
            jLabel6.setBackground(new Color(153,153,153));
        }else{
            int position = 2;
            selector(position);
        
            /* Show Jpanel5 */ 
            jPanel5.show();
            packageClick = true;
            
            /* Hide Jpanel4 */
            jPanel4.hide();
            userClick = false;
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel1MouseClicked(MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        int position = 0;
        selector(position);
        hideAll();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel10MouseClicked(MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        jDialog1.setSize(new Dimension(848, 521));
        jDialog1.setLocationRelativeTo(null);
        jDialog1.show();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    public void hideAll(){
            
        /* Hide Jpanel5 */
        jPanel5.hide();
        packageClick = false;
        
            
        /* Hide Jpanel4 */
        jPanel4.hide();
        userClick = false;
    }
    
    public void selector(int position){
        JLabel[] labelColor = {jLabel1,jLabel2,jLabel6};
        for (JLabel jLabel : labelColor) {
            /* Default Label Color*/
            jLabel.setBackground(new Color(153,153,153));
        }
        labelColor[position].setBackground(Color.red);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    JDialog jDialog1;
    JInternalFrame jInternalFrame1;
    JLabel jLabel1;
    JLabel jLabel10;
    JLabel jLabel11;
    JLabel jLabel2;
    JLabel jLabel3;
    JLabel jLabel4;
    JLabel jLabel6;
    JLabel jLabel7;
    JLabel jLabel8;
    JPanel jPanel1;
    JPanel jPanel2;
    JPanel jPanel3;
    JPanel jPanel4;
    JPanel jPanel5;
    JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
